[package]
name = "pagerank"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
config = "0.14.1" # https://github.com/mehcode/config-rs/issues/531
serde = "1.0.215"
serde_json = "1.0.132"
textwrap = "0.16.0"
