[package]
name = "pagerank"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
config = "0.13.4" # https://github.com/mehcode/config-rs/issues/531
serde = "1.0.210"
serde_json = "1.0.132"
textwrap = "0.16.0"
