[package]
name = "cli-customize-fruit-salad"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.1"
rand = "0.8.5"

[lib]
name = "fruit_salad_maker"
path = "src/lib.rs"
